Repository codeit-team-project/taskify, pull requests merged in 2023-12, with the labels that each got.

#5 [설정] 폰트, 색상, reset 스타일 적용
  package-lock.json
  package.json
  public/font/Pretendard/Pretendard-Black.woff2
  public/font/Pretendard/Pretendard-Bold.woff2
  public/font/Pretendard/Pretendard-ExtraBold.woff2
  public/font/Pretendard/Pretendard-ExtraLight.woff2
  public/font/Pretendard/Pretendard-Light.woff2
  public/font/Pretendard/Pretendard-Medium.woff2
  public/font/Pretendard/Pretendard-Regular.woff2
  public/font/Pretendard/Pretendard-SemiBold.woff2
  public/font/Pretendard/Pretendard-Thin.woff2
  public/font/Pretendard/pretendard.css
  public/next.svg
  public/vercel.svg
  src/pages/_app.tsx
  src/pages/_document.tsx
  src/pages/api/hello.ts
  src/pages/dashboard/index.tsx
  src/pages/index.tsx
  src/pages/my/index.tsx
  src/pages/signin/index.tsx
  src/pages/signup/index.tsx
  src/styles/Home.module.css
  src/styles/globals.css
  src/styles/reset.css
  yarn.lock
Labels: ⚙️Chore

#9 PR 템플릿, Issue 템플릿 추가
  .github/issue_template.md
  .github/pull_request_template.md
Labels: 📖Docs

#18 Feat(styles): mixin 변수 생성
  src/styles/mixin.scss
Labels: ⚙️Chore, 🌈Design

#24 [Refactor] MainNav 바 수정
  src/components/index.tsx
  src/components/mainNav/MainNav.module.scss
  src/components/mainNav/MainNav.tsx
Labels: ✏️Refactor

#20 Feature/invited 데스크톱 UI 구현
  .gitignore
  next.config.js
  public/assets/icon-no-invitation.png
  public/assets/icon-search.png
  src/components/invitedDashBoard/InvitedDashBoard.module.scss
  src/components/invitedDashBoard/InvitedDashBoard.tsx
  src/pages/mydashboard/index.tsx
  src/types/invitedDashBoardListType.ts
Labels: 🌟Feat, 🌈Design

#22 [Feat - 사이드바] Feature/sidebar
  public/assets/add_box.svg
  public/assets/crown_icon.svg
  public/assets/large_Taskify.svg
  public/assets/large_logo.svg
  src/components/sidebar/Sidebar.module.scss
  src/components/sidebar/Sidebar.tsx
  src/components/sidebar/SidebarItem.tsx
  src/components/ui/icons/Ellipse.tsx
  src/mock/dashBoard.ts
Labels: 🌈Design

#28 [Feat] footer 컴포넌트 생성
  public/assets/images/footer-facebook.svg
  public/assets/images/footer-instargram.svg
  public/assets/images/footer-msg.svg
  src/components/footer/Footer.module.scss
  src/components/footer/Footer.tsx
Labels: 🌈Design

#23 [Feat] 대시보드 nav 바 컴포넌트 생성
  next.config.js
  public/assets/addIcon.svg
  public/assets/settingIcon.svg
  src/components/dashboardNav/DashboardNav.module.scss
  src/components/dashboardNav/DashboardNav.tsx
  src/components/dashboardNav/dashboardNavEditor/DashboardNavEditor.module.scss
  src/components/dashboardNav/dashboardNavEditor/DashboardNavEditor.tsx
  src/components/dashboardNav/dropdown/Dropdown.module.scss
  src/components/dashboardNav/dropdown/Dropdown.tsx
  src/components/dashboardNav/mockup.ts
  src/components/dashboardNav/navProfile/NavProfile.module.scss
  src/components/dashboardNav/navProfile/NavProfile.tsx
  src/components/index.ts
  src/hooks/useDropdown.tsx
  src/types/MemberType.tsx
Labels: 🌟Feat, 🌈Design

#33 [Setting api] api 관련 작업
  next.config.js
  package.json
  src/api/auth/createLogin.ts
  src/api/auth/editPassword.ts
  src/api/columns/createColumn.ts
  src/api/columns/createColumnImageUpload.ts
  src/api/columns/deleteColumn.ts
  src/api/columns/editColumn.ts
  src/api/columns/getColumns.ts
  src/api/dashboards/createDashboards.ts
  src/api/dashboards/createDashboardsInvitations.ts
  src/api/dashboards/deleteDashboards.ts
  src/api/dashboards/editDashboards.ts
  src/api/dashboards/getDashboards.ts
  src/api/dashboards/getDashboardsDetail.ts
  src/api/dashboards/getDashboardsInvitations.ts
  src/api/invitations/getInvitations.ts
  src/api/invitations/putInvitations.ts
  src/api/members/deleteMembers.ts
  src/api/members/getMembers.ts
  src/api/users/createUser.ts
  src/api/users/createUserImageUpload.ts
  src/api/users/editUser.ts
  src/api/users/getUser.ts
  src/commons/lib/axiosInstance.ts
  src/components/ApiTest.tsx
  src/pages/_app.tsx
  src/types/auth.ts
  src/types/columnsType.ts
  src/types/dashBoardType.ts
  src/types/invitations.ts
  src/types/invitedDashBoardListType.ts
  src/types/members.ts
  src/types/users.ts
  yarn.lock
Labels: ⚙️Chore, 🥹Help

#36 [Design] 레이아웃 컴포넌트 생성
  src/components/dashboardNav/DashboardNav.module.scss
  src/components/dashboardNav/DashboardNav.tsx
  src/components/dashboardNav/dashboardNavEditor/DashboardNavEditor.module.scss
  src/components/dashboardNav/dashboardNavEditor/DashboardNavEditor.tsx
  src/components/dashboardNav/navProfile/NavProfile.module.scss
  src/components/footer/Footer.module.scss
  src/components/mainNav/MainNav.module.scss
  src/components/ui/layout/DashboardLayout.tsx
  src/components/ui/layout/HomeLayout.tsx
  src/components/ui/layout/Layout.module.scss
  src/components/ui/layout/MypageLayout.tsx
  src/pages/dashboard/index.tsx
  src/pages/index.tsx
  src/pages/my/index.tsx
  src/styles/mixin.scss
Labels: 🌈Design

#26 [Feat] signin, signup 페이지에 들어갈 form 컴포넌트 생성
  package.json
  public/assets/images/closeEye.svg
  public/assets/images/openEye.svg
  src/components/signForm/SignForm.module.scss
  src/components/signForm/SigninForm.tsx
  src/components/signForm/SignupForm.tsx
  src/components/signInput/PasswordInput.tsx
  src/components/signInput/SignInput.module.scss
  src/components/signInput/TextInput.tsx
  src/types/auth.ts
  src/types/formTypes.ts
  src/utils/formInputValidationRules.ts
  src/utils/regExpressions.ts
  yarn.lock
Labels: 🌟Feat, 🌈Design

#39 [Feat] Feature/sidebar
  src/components/sidebar/Sidebar.module.scss
  src/components/sidebar/Sidebar.tsx
  src/components/sidebar/SidebarItem.tsx
  src/mock/dashBoard.ts
Labels: 🌟Feat, 🌈Design

#43 [Feat] Feature/dashboard member
  package.json
  public/arrow_forward.svg
  public/arrow_next.svg
  public/circle.svg
  src/api/members/deleteMembers.ts
  src/api/members/getMembers.ts
  src/components/members/Member.module.scss
  src/components/members/MemberItem.tsx
  src/components/members/MemberList.tsx
  src/components/pagination/Pagination.module.scss
  src/components/pagination/Pagination.tsx
  src/pages/_app.tsx
  src/styles/globals.scss
  yarn.lock
Labels: 🌟Feat, 🌈Design

#45 [Feat] signin, signout 페이지, auth context(accessToken) 제작 및 리팩토링
  public/assets/Spinner-1s-200px.gif
  src/api/auth/createLogin.ts
  src/api/users/createUser.ts
  src/components/loadingSpinner/LoadingSpinner.module.scss
  src/components/loadingSpinner/LoadingSpinner.tsx
  src/components/serviceCheckInput/ServiceCheckInput.module.scss
  src/components/serviceCheckInput/ServiceCheckInput.tsx
  src/components/signForm/SignForm.module.scss
  src/components/signForm/SigninForm.tsx
  src/components/signForm/SignupForm.tsx
  src/components/signInput/SignInput.module.scss
  src/components/ui/layout/Layout.module.scss
  src/components/ui/layout/SignLayout.tsx
  src/contexts/AuthContext.tsx
  src/hooks/useAuth.ts
  src/pages/_app.tsx
  src/pages/signin/index.tsx
  src/pages/signup/index.tsx
  src/types/auth.ts
  src/types/formTypes.ts
  src/types/users.ts
Labels: ✏️Refactor, 🌈Design

#48 [Feat] axios interceptors 코드 및 user 전역 객체 추가
  package.json
  src/commons/lib/axiosInstance.ts
  src/components/signForm/SigninForm.tsx
  src/components/signForm/SignupForm.tsx
  src/contexts/AuthContext.tsx
  src/hooks/useAuth.ts
  src/pages/_app.tsx
  src/utils/cookie.ts
  yarn.lock
Labels: ⚙️Chore, 🌟Feat

#47 [Feat] Feature/dashboard invitations
  public/assets/add_box_white.svg
  src/api/dashboards/deleteDashboardsInvitations.ts
  src/api/dashboards/getDashboardsInvitations.ts
  src/components/invitations/Invitation.module.scss
  src/components/invitations/InvitationItem.tsx
  src/components/invitations/InvitationList.tsx
  src/components/invitations/InvitationModal.module.scss
  src/components/invitations/InvitationModal.tsx
  src/types/invitedDashBoardListType.ts
Labels: 🌟Feat, 🌈Design, 🥹Help

#44 Feture/invitation search accept
  src/api/invitations/getInvitations.ts
  src/api/invitations/putInvitation.ts
  src/components/invitedDashBoard/InvitedDashBoard.module.scss
  src/components/invitedDashBoard/InvitedDashBoard.tsx
  src/hooks/useDebounce.tsx
  src/hooks/useDidMountEffect.tsx
  src/pages/mydashboard/index.tsx
  src/types/invitations.ts
  src/types/invitedDashBoardListType.ts
Labels: 🌟Feat, 🌈Design

#53 [Feat] Feature/dashboard - 대시보드 생성 모달, 수정 컴포넌트
  public/assets/checkIcon.svg
  src/api/dashboards/createDashboards.ts
  src/api/dashboards/editDashboards.ts
  src/components/colorPicker/ColorPicker.module.scss
  src/components/colorPicker/ColorPicker.tsx
  src/components/colorPicker/dashBoardColorPalette.ts
  src/components/dashboard/EditDashboard.module.scss
  src/components/dashboard/EditDashboard.tsx
  src/components/dashboard/NewDashboardModal.module.scss
  src/components/dashboard/NewDashboardModal.tsx
  src/components/index.ts
  src/components/sidebar/Sidebar.tsx
  src/components/sidebar/SidebarItem.tsx
  src/pages/dashboard/[id]/edit/index.tsx
  src/pages/dashboard/[id]/index.tsx
  src/types/dashBoardType.ts
Labels: 🌟Feat, 🌈Design

#52 [Feat] 로그아웃 기능 구현
  next.config.js
  public/assets/no-profile.png
  src/components/dashboardNav/BoardNav.module.scss
  src/components/dashboardNav/DashboardNav.tsx
  src/components/dashboardNav/MyboardNav.tsx
  src/components/dashboardNav/dashboardNavEditor/DashboardNavEditor.tsx
  src/components/dashboardNav/dropdown/Dropdown.tsx
  src/components/dashboardNav/navProfile/NavProfile.module.scss
  src/components/dashboardNav/navProfile/NavProfile.tsx
  src/components/footer/Footer.tsx
  src/components/loadingSpinner/LoadingSpinner.tsx
  src/components/mainNav/MainNav.tsx
  src/components/ui/layout/DashboardLayout.tsx
  src/components/ui/layout/MypageLayout.tsx
  src/components/ui/layout/SignLayout.tsx
  src/pages/dashboard/index.tsx
Labels: 🌟Feat

#60 [Feat] 랜덤 프로필 생성 컴포넌트 제작
  src/components/randomProfile/RandomProfile.tsx
  src/components/ui/icons/Ellipse.tsx
Labels: 🌟Feat, 🌈Design

#61 [FIX] 랜덤 프로필 불필요한 중복 코드 삭제
  src/components/randomProfile/RandomProfile.tsx
Labels: 🔨Fix

#57 Feature/dashboard page - 대시보드 수정페이지
  src/components/dashboard/EditDashboard.module.scss
  src/components/dashboard/EditDashboard.tsx
  src/components/dashboardNav/BoardNav.module.scss
  src/components/invitations/Invitation.module.scss
  src/components/invitations/InvitationList.tsx
  src/components/members/Member.module.scss
  src/components/members/MemberItem.tsx
  src/components/members/MemberList.tsx
  src/components/pagination/Pagination.tsx
  src/components/randomProfile/RandomProfile.tsx
  src/components/sidebar/Sidebar.module.scss
  src/components/ui/icons/Ellipse.tsx
  src/components/ui/layout/Layout.module.scss
  src/components/ui/nodataUI/NodataUI.module.scss
  src/components/ui/nodataUI/NodataUI.tsx
  src/pages/dashboard/[id]/edit/index.module.scss
  src/pages/dashboard/[id]/edit/index.tsx
  src/styles/mixin.scss
Labels: 🌟Feat, 🌈Design

#65 [Chore] eslint rules 수정
  .eslintrc.json
Labels: ⚙️Chore, 🔨Fix

#62 [Feat] Feature/dashboard - 대시보드 목록 컴포넌트
  public/assets/add_fill_primary.svg
  src/api/dashboards/getDashboards.ts
  src/components/dashboard/DashboardItem.tsx
  src/components/dashboard/DashboardList.module.scss
  src/components/dashboard/DashboardList.tsx
  src/components/sidebar/Sidebar.tsx
  src/pages/mydashboard/index.tsx
Labels: 🌟Feat, 🌈Design

#59 [Feat] dashboard nav 기능, 디자인
  src/api/members/getMembers.ts
  src/components/dashboardNav/BoardNav.module.scss
  src/components/dashboardNav/DashboardNav.tsx
  src/components/dashboardNav/MyboardNav.tsx
  src/components/dashboardNav/dashboardNavEditor/DashboardNavEditor.module.scss
  src/components/dashboardNav/dashboardNavEditor/DashboardNavEditor.tsx
  src/components/dashboardNav/mockup.ts
  src/components/dashboardNav/navProfile/NavProfile.module.scss
  src/components/dashboardNav/navProfile/NavProfile.tsx
  src/components/ui/layout/DashboardLayout.tsx
  src/components/ui/layout/MypageLayout.tsx
  src/hooks/useDropdown.tsx
  src/pages/dashboard/[id]/edit/index.tsx
  src/pages/dashboard/[id]/index.tsx
  src/pages/dashboard/index.tsx
  src/types/MemberType.tsx
  src/utils/cookie.ts
Labels: 🌟Feat

#54 [Feat] myPage 생성
  public/assets/no-profile2.png
  src/api/users/createUserImageUpload.ts
  src/commons/lib/axiosInstance.ts
  src/components/editForm/EditFormLayout.module.scss
  src/components/editForm/EditFormLayout.tsx
  src/components/editForm/passwordModifier/PasswordModifier.module.scss
  src/components/editForm/passwordModifier/PasswordModifier.tsx
  src/components/editForm/profile/Profile.module.scss
  src/components/editForm/profile/Profile.tsx
  src/components/editForm/profile/imageUploader/ImageUploader.module.scss
  src/components/editForm/profile/imageUploader/ImageUploader.tsx
  src/components/signInput/ReadonlyInput.tsx
  src/components/ui/layout/Layout.module.scss
  src/pages/my/index.tsx
  src/types/formTypes.ts
  src/types/users.ts
  src/utils/cookie.ts
  src/utils/formInputValidationRules.ts
Labels: 🌟Feat, 🌈Design

#67 [Feat] sign page 디자인 수정
  src/components/signForm/SignForm.module.scss
  src/components/signForm/SigninForm.tsx
  src/components/signForm/SignupForm.tsx
  src/components/ui/layout/Layout.module.scss
  src/components/ui/layout/SignLayout.tsx
  src/pages/_app.tsx
  src/pages/signin/index.tsx
  src/pages/signup/index.tsx
Labels: 🌈Design

#73 Feat: 컬럼 UI 추가 데이터 연동X 반응형O
  public/assets/icon-add-purple.png
  public/assets/icon-calendar.png
  src/components/columns/addColumnButton/AddColumnButton.module.scss
  src/components/columns/addColumnButton/AddColumnButton.tsx
  src/components/columns/addTaskButton/AddTaskButton.module.scss
  src/components/columns/addTaskButton/AddTaskButton.tsx
  src/components/columns/columnItem/ColumnItem.module.scss
  src/components/columns/columnItem/ColumnItem.tsx
  src/components/columns/columnList/ColumnList.module.scss
  src/components/columns/columnList/ColumnList.tsx
  src/components/columns/columnTitle/ColumnTitle.module.scss
  src/components/columns/columnTitle/ColumnTitle.tsx
  src/components/columns/taskCardItem/TaskCardItem.module.scss
  src/components/columns/taskCardItem/TaskCardItem.tsx
  src/components/columns/taskCardList/TaskCardList.module.scss
  src/components/columns/taskCardList/TaskCardList.tsx
  src/pages/dashboard/index.tsx
Labels: 🌈Design

#66 [Design] landing page 제작
  public/assets/homeImgs/desktop.png
  public/assets/homeImgs/img1.png
  public/assets/homeImgs/img11.png
  public/assets/homeImgs/img2.png
  public/assets/homeImgs/img22.png
  public/assets/homeImgs/img33.png
  src/components/footer/Footer.module.scss
  src/components/mainNav/MainNav.module.scss
  src/components/styledDescription/StyledDescription.module.scss
  src/components/styledDescription/StyledDescription.tsx
  src/pages/Homepage.module.scss
  src/pages/index.tsx
Labels: 🌈Design

#76 Feature/invited dashboard2
  src/api/invitations/putInvitation.ts
  src/components/invitedDashBoard/InvitedDashBoard.module.scss
  src/components/invitedDashBoard/InvitedDashBoard.tsx
  src/pages/mydashboard/index.tsx
  src/types/invitations.ts
Labels: ✏️Refactor, 🥹Help
