Repository codeit-team-project/taskify, pull requests merged in 2024-01, with the labels that each got.

#79 Feat: 컬럼 리스트 api 연동
  src/api/card/getCards.ts
  src/api/columns/getColumns.ts
  src/components/columns/columnItem/ColumnItem.tsx
  src/components/columns/columnList/ColumnList.tsx
  src/components/columns/taskCardItem/TaskCardItem.module.scss
  src/components/columns/taskCardItem/TaskCardItem.tsx
  src/components/columns/taskCardList/TaskCardList.module.scss
  src/components/columns/taskCardList/TaskCardList.tsx
  src/pages/dashboard/[id]/index.tsx
  src/pages/dashboard/index.tsx
  src/types/cardsType.ts
Labels: 🌟Feat

#75 [Feat & Design] Feature/sidebar
  src/components/sidebar/Sidebar.module.scss
  src/components/sidebar/Sidebar.tsx
  src/components/sidebar/SidebarItem.tsx
Labels: 🌟Feat, 🌈Design

#69 modal에 들어가는 modalInput관련 컴퍼넌트
  package.json
  public/assets/images/arrowDown.svg
  public/assets/images/calendar.svg
  public/assets/images/check.svg
  public/assets/images/close.svg
  public/assets/images/divider.svg
  public/assets/images/kebab.svg
  public/assets/images/plusImage.svg
  src/components/modalInput/ColumnName.module.scss
  src/components/modalInput/ColumnName.tsx
  src/components/modalInput/DeadLine.module.scss
  src/components/modalInput/DeadLine.tsx
  src/components/modalInput/DeadLineInput.module.scss
  src/components/modalInput/DeadLineInput.tsx
  src/components/modalInput/DesCription.module.scss
  src/components/modalInput/DesCription.tsx
  src/components/modalInput/ImageUpload.module.scss
  src/components/modalInput/ImageUpload.tsx
  src/components/modalInput/Manager.module.scss
  src/components/modalInput/Manager.tsx
  src/components/modalInput/Tags.module.scss
  src/components/modalInput/Tags.tsx
  src/components/modalInput/Title.module.scss
  src/components/modalInput/Title.tsx
  src/context/formContext.tsx
  src/utils/mappingTime.ts
  src/utils/modalInputValidation.ts
  src/utils/resetFormState.ts
Labels: 🌟Feat, 🌈Design

#83 [Feat] authentication 을 위한 미들웨어 추가
  src/middleware.ts
Labels: 🌟Feat

#82 할일모달에서의 column이름과 tag값을 나타내는 컴퍼넌트
  .gitignore
  src/components/modalHeader/ModalHeader.module.scss
  src/components/modalHeader/ModalHeader.tsx
Labels: 🌟Feat, 🌈Design

#77 [Fix & Design] Feature/dashboard invitations
  src/components/dashboard/DashboardList.tsx
  src/components/dashboard/NewDashboardModal.tsx
  src/components/invitations/InvitationList.tsx
  src/components/members/Member.module.scss
  src/components/members/MemberItem.tsx
Labels: 🌈Design

#80 [Feat] Feature/column modal - 컬럼 생성 모달
  src/components/columns/columnModal/CreateColumnModal.module.scss
  src/components/columns/columnModal/CreateColumnModal.tsx
Labels: 🌟Feat, 🌈Design

#87 할일생성 모달에서 business logic을 처리하는 컴퍼넌트
  src/api/cards/createCard.ts
  src/api/cards/deleteCard.ts
  src/api/cards/editCard.ts
  src/api/cards/getCardDetail.ts
  src/api/cards/getCards.ts
  src/api/columns/createColumnImageUpload.ts
  src/data-access/createTodo/CreateTodo.module.scss
  src/data-access/createTodo/CreateTodo.tsx
  src/types/columnsType.ts
  src/types/commentType.ts
Labels: 🌟Feat, 🌈Design

#91 할일수정모달에서 business logic을 처리하는 컴퍼넌트
  src/data-access/editTodo/EditTodo.module.scss
  src/data-access/editTodo/EditTodo.tsx
Labels: 🌟Feat, 🌈Design

#92 할일상세모달에서 business logic을 처리하는 컴퍼넌트
  src/api/cards/editCard.ts
  src/api/comments/createComments.ts
  src/api/comments/deleteComments.ts
  src/api/comments/editComments.ts
  src/api/comments/getComments.ts
  src/components/modalComment/ModalComment.module.scss
  src/components/modalComment/ModalComment.tsx
  src/data-access/editTodo/EditTodo.tsx
  src/data-access/readTodo/ReadTodo.module.scss
  src/data-access/readTodo/ReadTodo.tsx
  src/hooks/useComponentVisible.tsx
  src/hooks/userScroll.tsx
Labels: 🌟Feat, 🌈Design

#93 Fix: 초대받은 대시보드 개선
  src/components/invitedDashBoard/InvitedDashBoard.module.scss
  src/components/invitedDashBoard/InvitedDashBoard.tsx
  src/types/invitedDashBoardListType.ts
Labels: ✏️Refactor, 🔨Fix

#94 Fix: 오류 수정 & randomProfile component적용
  src/components/modalComment/ModalComment.module.scss
  src/components/modalComment/ModalComment.tsx
  src/components/modalInput/Manager.tsx
  src/components/modalProfile/ModalProfile.tsx
  src/data-access/readTodo/ReadTodo.tsx
  src/hooks/useScroll.tsx
Labels: 🌟Feat, 🌈Design

#89 [Feat] nav 디자인 수정 및 floating 버튼 추가
  public/assets/images/addIcon.svg
  public/assets/images/settingIcon.svg
  src/components/dashboardNav/BoardNav.module.scss
  src/components/dashboardNav/dashboardNavEditor/DashboardNavEditor.module.scss
  src/components/dashboardNav/dashboardNavEditor/DashboardNavEditor.tsx
  src/components/dashboardNav/floatingButton/FloatingButton.module.scss
  src/components/dashboardNav/floatingButton/FloatingButton.tsx
Labels: 🌟Feat, 🌈Design

#95 [Feat & Design] Feature/dashboard page - 모달 연동, 스타일 수정
  src/components/colorPicker/ColorPicker.module.scss
  src/components/columns/addColumnButton/AddColumnButton.tsx
  src/components/columns/columnList/ColumnList.tsx
  src/components/columns/columnModal/CreateColumnModal.tsx
  src/components/dashboard/DashboardList.module.scss
  src/components/dashboard/DashboardList.tsx
  src/components/dashboard/EditDashboard.tsx
  src/components/dashboard/NewDashboardModal.tsx
  src/components/dashboardModal/ModalContainer.module.scss
  src/components/dashboardModal/ModalContainer.tsx
  src/components/dashboardNav/dashboardNavEditor/DashboardNavEditor.tsx
  src/components/invitations/InvitationList.tsx
  src/components/invitations/InvitationModal.tsx
  src/components/invitedDashBoard/InvitedDashBoard.module.scss
  src/components/invitedDashBoard/InvitedDashBoard.tsx
  src/components/members/Member.module.scss
  src/components/members/MemberList.tsx
  src/components/sidebar/Sidebar.tsx
  src/components/ui/layout/Layout.module.scss
  src/pages/dashboard/index.tsx
  src/pages/mydashboard/index.module.scss
  src/pages/mydashboard/index.tsx
  src/styles/globals.scss
Labels: 🌟Feat, 🌈Design

#96 [Design] 에러 페이지 생성
  public/assets/error.png
  src/pages/404.tsx
  src/pages/index.tsx
  src/styles/Homepage.module.scss
  src/styles/NotFound.module.scss
Labels: 🌟Feat, 🌈Design

#102 Feat: 컬럼 관리 모달 구현
  src/components/columns/TaskCardItem/TaskCardItem.module.scss
  src/components/columns/TaskCardItem/TaskCardItem.tsx
  src/components/columns/addTaskButton/AddTaskButton.tsx
  src/components/columns/columnItem/ColumnItem.module.scss
  src/components/columns/columnItem/ColumnItem.tsx
  src/components/columns/columnList/ColumnList.tsx
  src/components/columns/columnModal/ManageColumnModal.module.scss
  src/components/columns/columnModal/ManageColumnModal.tsx
  src/components/columns/columnTitle/ColumnTitle.module.scss
  src/components/columns/columnTitle/ColumnTitle.tsx
  src/components/columns/manageColumnButton/ManageColumnButton.module.scss
  src/components/columns/manageColumnButton/ManageColumnButton.tsx
  src/components/columns/taskCardList/TaskCardList.module.scss
  src/components/columns/taskCardList/TaskCardList.tsx
  src/components/modalHeader/ModalHeader.tsx
  src/components/randomProfile/RandomProfile.tsx
Labels: 🌟Feat, 🌈Design

#99 [Feat] 토스트 메세지 컴포넌트 생성
  package.json
  src/components/customToast/CustomToast.module.scss
  src/components/customToast/CustomToast.tsx
  src/components/dashboardNav/dropdown/Dropdown.tsx
  src/components/editForm/passwordModifier/PasswordModifier.tsx
  src/components/editForm/profile/Profile.tsx
  src/components/signForm/SigninForm.tsx
  src/components/signForm/SignupForm.tsx
  src/pages/_app.tsx
  yarn.lock
Labels: 🌈Design

#106 [Settings] 매타데이터 생성
  public/favicon.ico
  src/components/headMeta/HeadMeta.tsx
  src/pages/_app.tsx
  src/pages/dashboard/[id]/index.tsx
Labels: ⚙️Chore, ✏️Refactor

#104 Refactor: 공통 레이아웃 수정, 플로팅 버튼 위치 개선
  src/components/columns/addColumnButton/AddColumnButton.module.scss
  src/components/columns/addColumnButton/AddColumnButton.tsx
  src/components/columns/columnList/ColumnList.module.scss
  src/components/dashboardNav/floatingButton/FloatingButton.module.scss
  src/components/invitedDashBoard/InvitedDashBoard.module.scss
  src/components/ui/layout/Layout.module.scss
  src/pages/dashboard/[id]/edit/index.module.scss
  src/pages/my/index.module.scss
  src/pages/my/index.tsx
  src/pages/mydashboard/index.module.scss
Labels: 🌈Design

#109 Docs: 리드미 기본 생성
  README.md
  public/assets/image-1.png
  public/assets/sample/board-card-3.png
  public/assets/sample/board-card-comment.png
  public/assets/sample/board-card-edit.png
  public/assets/sample/board-card.png
  public/assets/sample/board-delete.png
  public/assets/sample/board-edit.png
  public/assets/sample/board-new.png
  public/assets/sample/board-page.png
  public/assets/sample/dash-invite.png
  public/assets/sample/dash-page.png
  public/assets/sample/error-404.png
  public/assets/sample/error-dashboard.png
  public/assets/sample/error-signin.png
  public/assets/sample/error-signup.png
  public/assets/sample/failed-signin.png
  public/assets/sample/failed-signup.png
  public/assets/sample/image-1.png
  public/assets/sample/image-2.png
  public/assets/sample/image-3.png
  public/assets/sample/image.png
  public/assets/sample/main-mobile.png
  public/assets/sample/mydashboard-create.png
  public/assets/sample/mydashboard-drop.png
  public/assets/sample/mydashboard-initial.png
  public/assets/sample/mydashboard-invite.png
  public/assets/sample/mydashboard-used.png
  public/assets/sample/mypage-profile.png
  public/assets/sample/mypage-psw.png
  public/assets/sample/not-owner.png
  public/assets/sample/yes-owner.png
Labels: 📖Docs

#110 [Style] Feature/dashboard page - 주석정리, 파일제거, 기타 오류 수정
  package.json
  src/components/ApiTest.tsx
  src/components/dashboardNav/dashboardNavEditor/DashboardNavEditor.tsx
  src/pages/my/index.tsx
  src/pages/mydashboard/index.tsx
  src/pages/signin/index.tsx
  src/pages/signup/index.tsx
Labels: 🔨Fix

#111 [Style] 플로팅 버튼 디자인 일부 수정
  src/components/dashboardNav/floatingButton/FloatingButton.module.scss
  src/components/dashboardNav/floatingButton/FloatingButton.tsx
  src/hooks/useDropdown.tsx
Labels: 🌈Design

#113 [Feat] 이용약관 모달 생성
  src/components/editForm/profile/imageUploader/ImageUploader.tsx
  src/components/loadingSpinner/LoadingSpinner.tsx
  src/components/mainNav/MainNav.tsx
  src/components/serviceCheckInput/ServiceCheckInput.module.scss
  src/components/serviceCheckInput/ServiceCheckInput.tsx
  src/components/ui/layout/HomeLayout.tsx
  src/types/auth.ts
Labels: 🌈Design

#116 Fix: dueDate 포맷 변경
  src/components/columns/TaskCardItem/TaskCardItem.tsx
Labels: 🔨Fix

#118 Fix: 세세한 ui 수정
  src/components/columns/TaskCardItem/TaskCardItem.module.scss
  src/components/columns/TaskCardItem/TaskCardItem.tsx
  src/components/invitedDashBoard/InvitedDashBoard.module.scss
Labels: 🌈Design

#119 Fix: 대시보드 생성 모달 점검
  src/components/dashboard/NewDashboardModal.tsx
  src/components/sidebar/Sidebar.tsx
Labels: 🔨Fix

#120 Fix: 스크롤 바닥 인지 못하는 현상 해결
  src/components/invitedDashBoard/InvitedDashBoard.module.scss
  src/components/invitedDashBoard/InvitedDashBoard.tsx
Labels: 🔨Fix

#121 [feat: 버튼활성화색상추가 & 날짜 readonly로 변경]
  src/components/modalButton/ModalButton.module.scss
  src/components/modalButton/ModalButton.tsx
  src/components/modalInput/DeadLineInput.tsx
Labels: 🌈Design

#122 Fix: z index 디자인 일부 수정 및 쿼리 키 수정
  src/components/dashboardModal/ModalContainer.module.scss
  src/components/dashboardNav/BoardNav.module.scss
  src/components/dashboardNav/navProfile/NavProfile.tsx
  src/components/modalContent/ModalContent.module.scss
  src/components/sidebar/Sidebar.module.scss
Labels: 🔨Fix

#123 Develop to Main
  src/components/dashboardModal/ModalContainer.module.scss
  src/components/dashboardNav/BoardNav.module.scss
  src/components/dashboardNav/navProfile/NavProfile.tsx
  src/components/invitedDashBoard/InvitedDashBoard.module.scss
  src/components/invitedDashBoard/InvitedDashBoard.tsx
  src/components/modalButton/ModalButton.module.scss
  src/components/modalButton/ModalButton.tsx
  src/components/modalContent/ModalContent.module.scss
  src/components/modalInput/DeadLineInput.tsx
  src/components/sidebar/Sidebar.module.scss
Labels: 📄Test
